services:
  pgsql:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - trackr-network

  api:
    build: ./trackr-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://pgsql:5432/${POSTGRES_DB}
    ports:
      - "8080:8080"
    depends_on:
      - pgsql
    networks:
      - trackr-network

  frontend:
      build: ./trackr-frontend
      ports:
        - "3000:3000"
      networks:
        - trackr-network

networks:
  trackr-network: